name: Run pytest in matrix

on:
  push:
  pull_request:

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          poetry install

      - name: Run Unit Tests (pytest)
        env:
          python-version: ${{ matrix.python-version }}
          CONFIDENT_AI_API_KEY: ${{ secrets.API_KEY_ENV }}
        run: |
          poetry run deepeval test run -x tests
